name: The Rust Programming Language
stable: "1.21.0"
stable_date: "2017-10-12"
stable_blog: "https://blog.rust-lang.org/2017/10/12/Rust-1.21.html"
stable_full_version: "rustc 1.21.0 (3b72af97e 2017-10-09)"
beta: "1.22"
beta_date: "2017-11-23"
nightly: "1.23"
channels:
  - name: "stable"
    vers: "1.21.0"
    package: "1.21.0"
  - name: "beta"
    vers: "1.22"
    package: "beta"
  - name: "nightly"
    vers: "1.23"
    package: "nightly"
