name: The Rust Programming Language
stable: "1.15.1"
stable_date: "2017-02-09"
stable_blog: "https://blog.rust-lang.org/2017/02/09/Rust-1.15.1.html"
stable_full_version: "rustc 1.15.1 (021bd294c 2017-02-08)"
beta: "1.16"
beta_date: "2017-03-16"
nightly: "1.17"
channels:
  - name: "stable"
    vers: "1.15.1"
    package: "1.15.1"
  - name: "beta"
    vers: "1.16"
    package: "beta"
  - name: "nightly"
    vers: "1.17"
    package: "nightly"
