name: The Rust Programming Language
stable: "1.26.2"
stable_date: "2018-06-05"
stable_blog: "https://blog.rust-lang.org/2018/06/05/Rust-1.26.2.html"
stable_full_version: "rustc 1.26.2 (827013a31 2018-05-25)"
beta: "1.27"
beta_date: "2018-06-21"
nightly: "1.28"
channels:
  - name: "stable"
    vers: "1.26.2"
    package: "1.26.2"
  - name: "beta"
    vers: "1.27"
    package: "beta"
  - name: "nightly"
    vers: "1.28"
    package: "nightly"
